# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Clc2Manning
                                 A QGIS plugin
 Extrae el manning para HECRAS del CORINE2018
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-12
        copyright            : (C) 2026 by Pedro y Hugo Bohorquez
        email                : pedroiba94@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Clc2Manning class from file Clc2Manning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Mod1 import Clc2Manning
    return Clc2Manning(iface)
